BeastAi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views

# from django.conf.urls import url
from django.conf import settings
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.home, name='home'), 
    path('projects/', include('projects.urls')),
    path('donate/', views.donate, name='donate'),
    path('cancel/', views.cancel, name='cancel'),

    path('success/', views.success, name='success'),
    path('thankyouforsubmitting/', views.thankyouforsubmitting, name='thankyouforsubmitting'),
    path('hii/', views.hii, name='hii'),
        # path('hii/recording', views.record, name='record')




]


projects/urls.py
from django.urls import path
from . import views




app_name = 'projects'


#domain.com/projects/track_teacher_performance
urlpatterns = [ 
               
    path('track_teacher_performance/', views.track_teacher, name='track_teacher'),
    path('generatingExamUsingGPT/', views.examGPT, name = 'examGPT'), 
    # path('generatingExamUsingGPT/whisper/', views.examGPT_voice, name = 'examGPT_voice'),
    # path('generatingExamUsingGPT/whisper/record/', views.record, name = 'record'), 
 

    path('generatingExamUsingGPT/download_exam', views.download_exam, name='download_exam'), #project
    path('generatingExamUsingGPT/download_exam_arabic', views.download_exam_arabic, name='download_exam_arabic'), #project

    
    path('generatingExamUsingGPT/download_exam_answers', views.download_exam_answers, name = 'download_answers'), 
    # path('generatingExamUsingGPT/download_exam_whisper', views.download_exam_whisper, name='download_exam_whisper'), #project
    # path('generatingExamUsingGPT/download_exam_answers_whisper', views.download_exam_answers_whisper, name='download_exam_answers_whisper'), #project

    path('signup/', views.signup, name='signup'), 
    path('track_teacher_performance/sendReport', views.send_trackTeachers, name='send_trackTeachers'),
    path('track_teacher_performance/download_teachers_report', views.download_teachers_report, name='download_teachers_report'),

    
    
    path('generatingLessonPlanUsingGPT/', views.LessonPlanGPT, name = 'LessonPlanGPT'), 
    path('generatingLessonPlanUsingGPT/download_lessonPlan', views.download_lessonPlan, name = 'download_lessonPlan'), 



    
    
    # path('thankyou/', views.thank, name='thank'), 
    

 
    
]

projects/models.py
from django.db import models

# Create your models here.
import datetime
import os
from django.core.validators import MinValueValidator, MaxValueValidator

class ContactUs (models.Model):
    first_name_contact_us = models.CharField(max_length=120)
    last_name_contact_us = models.CharField(max_length=120)
    email_contact_us = models.EmailField()
    number_contact_us = models.IntegerField()
    inquiry_contact_us = models.CharField(max_length=5000)

    def __str__(self):
        return f'{self.first_name_contact_us} {self.last_name_contact_us} email {self.email_contact_us}.'
    
    
class TrackTeacherModel(models.Model):
    oldfile = models.FileField(upload_to='track_teachers/' )
    newfile = models.FileField(upload_to='track_teachers/')

    def __str__(self):
        return f'first is   {self.oldfile} and second  is  {self.newfile}'

topic_language = (('English', 'english'), 
                  ('Arabic', 'arabic'))

class ExamGPTModel(models.Model):
    lesson_name = models.CharField(max_length=300)
    subject = models.CharField(max_length=50)
    grade = models.CharField(max_length=12)
    school_name = models.CharField(max_length=100)
    teacher_name = models.CharField(max_length=60)
    topic_language =  models.CharField(choices=topic_language ,max_length=100)
    def __str__(self):
        return f'A teacher {self.teacher_name} created a Quiz about {self.lesson_name}'

class LessonPlanGPTModel(models.Model):
    lesson_name = models.CharField(max_length=500)
    subject = models.CharField(max_length=50)
    grade = models.CharField(max_length=12)
    school_name = models.CharField(max_length=100)
    teacher_name = models.CharField(max_length=60)
    def __str__(self):
        return f'A teacher {self.teacher_name} created a lesson plan about {self.lesson_name}'
    
    
    
class Donate(models.Model):
    full_name = models.CharField(max_length=120, default='unknown')
    email = models.EmailField(default='unknown mail')
    amount = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.full_name} donated {self.amount}."
    
    
class ExamGPTWhisperModel(models.Model):
    lesson_name = models.CharField(max_length=500)
    def __str__(self):
        return f'A teacher created a Quiz about {self.lesson_name}'
    
class LessonGPTWhisperModel(models.Model):
    lesson_name = models.CharField(max_length=500)
    def __str__(self):
        return f'A teacher created a lesson plan about {self.lesson_name}'

projects/forms.py
from django import forms
from django.forms import ModelForm







        
    
    

projects/views.py
import openai
import os

os.environ['OPENAI_API_KEY']= 'sk-L8cL3HKXIeQKCFU88N8kT3BlbkFJpSqXbs'
os.getenv('OPENAI_API_KEY')
openai.api_key = os.getenv('OPENAI_API_KEY')

from django.shortcuts import render, redirect 
from django.urls import reverse
from projects.models import TrackTeacherModel, ExamGPTModel, LessonPlanGPTModel
from projects.models import ExamGPTWhisperModel, LessonGPTWhisperModel
from django.contrib import messages
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None  # default='warn'
import docxtpl
from docxtpl import DocxTemplate
from django.http import HttpResponse
from docx import Document

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders


import docxtpl
from docxtpl import DocxTemplate
from datetime import date, datetime

global exam_path
global exam_path_arabic

global answers_path

#Using Bard APIs
# from bardapi import Bard
# #Replace XXXX with the values you get from __Secure-1PSID
# os.environ['_BARD_API_KEY']="ZAjh4qajOjkdj2hDildkr_2i3mMPKY-eYx3C6BTfGLDv6SY06YYFmPmhG87J1oFaGG_nPw."

# import requests
# from bardapi.constants import SESSION_HEADERS
# from bardapi import Bard

# token = "aQjh4oLDS577NwiuWce_NnZSnBIzFDrZAX81tlUNFn_OxKaZFrJc-xQJwCwKM448Td9W0g."
# session = requests.Session()
# session.headers = SESSION_HEADERS
# session.cookies.set("__Secure-1PSID", token)
# session.cookies.set("__Secure-1PSIDTS", "sidts-CjIBSAxbGXZloT1-ncoPFGy5qMPzAYczSjyGWoydXdnAip17kQU8sh6TlRQ2JI8_OMGGJRAA")
# session.cookies.set("__Secure-1PSIDCC", "APoG2W8wQn_T3mgEthQdz0XaGwBztbmh_OGl9UE5XtpiSxIYMDOh75nka-bE5ga6gEZ79RobeQ")
# bard = Bard(token=token, session=session)



def track_teacher(request):
    if request.method == "POST":
        old=(request.FILES['oldfile'])
        new=(request.FILES['newfile'])
        TrackTeacherModel.objects.create(oldfile=old, newfile=new).save()
        messages.success(request, "File uploaded successfully!")
            
        old_original = pd.read_excel(old)
        new_original = pd.read_excel(new)
        
        new_original  = new_original.sort_values('Email')
        old_original = old_original.set_index('Email')
        old_original = old_original[~old_original.index.duplicated()]
        old_original = old_original.reindex(index=new_original['Email'])
        old_original = old_original.reset_index()
        new_original = new_original.reset_index()

        columns = ['School Name', 'Full Name', 'Created Content', 'Created Discussions', 'No Of Posts', 'Question Counts In QB', 'Questions In Assessment', 'Assessments Count', 'Quizzes Count', 'InClass Activity Count', 'Added Materials On Space']
        old = old_original[columns]
        new = new_original[columns]
        old['total'] = old.iloc[:,2:].sum(axis=1)
        new['total'] = new.iloc[:,2:].sum(axis=1)
        columns.append('total')
        df_difference = pd.DataFrame()
        df_difference['School Name'] = new['School Name']
        df_difference['Full Name'] = new['Full Name']
        df_difference = df_difference.dropna()

        for i in columns[2:]:
            df_difference[i] = new[i] - old[i]

        # new = new.reset_index(drop=True)
        # new['Full Name'] = new['Full Name'].apply(lambda x:GoogleTranslator(source='en', target='ar').translate(x))

        for i, x in enumerate(new['Full Name']):
            if len(x.split(' '))>2:
                list_names = x.split(' ')
                new['Full Name'][i] = ' '.join([list_names[0], list_names[1],  list_names[-1]])
                
        df_difference['Full Name'] = new['Full Name']
        df_difference['total_new'] = new['total']
        df_difference['total_old'] = old['total']
        df_difference['Total Points'] = new_original['Total Points']
        
        df_sorted_total=df_difference.sort_values('Total Points')
        df_sorted_total_names  =df_sorted_total['Full Name']
        total_points = df_sorted_total['Total Points']
        total_new = df_sorted_total['total_new']
        total_old = df_sorted_total['total_old']
        difference = df_sorted_total['total']
        
        track_teachers_report = df_difference.copy()
        track_teachers_report = track_teachers_report[['Full Name', 'total']]
        track_teachers_report.columns = ['Full Name', 'Improvement Index' ]
        track_teachers_report['KG'] = track_teachers_report['Improvement Index'].apply(lambda x:'yes' if x>50 else 'No')
        track_teachers_report['C1'] = track_teachers_report['Improvement Index'].apply(lambda x:'yes' if x>100 else 'No')
        track_teachers_report['C2/C3'] = track_teachers_report['Improvement Index'].apply(lambda x:'yes' if x>150 else 'No')
        
        global track_teachers_report_path
        track_teachers_report_name = 'Report teacher performance' + ' '+ datetime.strftime(datetime.now(), '%Y-%m-%d-%H-%M-%S')
        track_teachers_report_path = 'media/track_teachers/'+track_teachers_report_name+'.xlsx'
        track_teachers_report.to_excel(track_teachers_report_path)
        if os.path.exists(track_teachers_report_path):
            report_exist = True

        background=[]
        background_difference = ['rgba(50, 255, 50, 1' if x>0 else 'rgba(255, 100, 100, 1' for x in df_sorted_total['total'] ]

        number_rows = len(df_difference)
        for x in range(number_rows):
            if x < np.round(number_rows/5):
                value = 'rgba(255, 0, 0, 1'
            elif x <np.round(number_rows/5)*2:
                value = 'rgba(255, 100, 100, 1'
            elif x <np.round(number_rows/5)*3:
                value = 'rgba(255, 255, 50, 1'
            elif x <np.round(number_rows/5)*4:
                value = 'rgba(50, 255, 50, 1'
            else:
                value = 'rgba(0, 150, 0, 1'

            background.append(value)
        
        global email_list
        email_list='engmohammadzahrawi1996@gmail.com,'
        for i in list(new_original['Email']):
            email_list = email_list+i+','
        new['% Created Content'] = (new['Created Content'] / new['total']) *100
        new['% Discussions'] = (new['Created Discussions'] / new['total']) *100
        new['% Posts'] = (new['No Of Posts'] / new['total']) *100

        new['% Questions in Banks'] = (new['Question Counts In QB'] / new['total']) *100
        new['% Questions in Assessments'] = (new['Questions In Assessment'] / new['total']) *100
        new['% assessments'] = (new['Assessments Count'] / new['total']) *100
        new['% quizzes'] = (new['Quizzes Count'] / new['total']) *100

        new['% Activity'] = (new['InClass Activity Count'] / new['total']) *100
        new['% Adding Materials'] = (new['Added Materials On Space'] / new['total']) *100

        pieChart_data = new[['% Created Content', '% Discussions', '% Posts','% Questions in Banks', '% Questions in Assessments', '% assessments', '% quizzes', '% Activity', '% Adding Materials' ]]
        pieChart_names= new['Full Name']
        data=[]
        for i in range(len(new)):
            data.append([round(x, 2) for x in list(pieChart_data.loc[i])])
        data = np.array(data)
        data = np.nan_to_num(data,0)
        data = data.tolist()
            
        pieChart_IDs = ['ID_' + str(x) for x in range(len(new))]
        config_id = ['config_' + str(x) for x in range(len(new))]
        data_id = ['data_' + str(x) for x in range(len(new))]
        combine = zip(pieChart_IDs, config_id, data_id)
        
        
        context = {'total_points':total_points, 'df_sorted_total_names':df_sorted_total_names, 'total_new':total_new, 
                   'total_old':total_old, 'background': background, 'background_difference':background_difference, 
                    'difference':difference, 'data' : data, 'pieChart_IDs':pieChart_IDs, 'pieChart_names':pieChart_names, 'combine':combine, 
                    'report_exist':report_exist}

        # context = {'total_points':total_points, 'df_sorted_total_names':df_sorted_total_names}
        return render(request, 'projects/track_teacher.html', context =context)
    
    else:
        context = {}
        return render(request, 'projects/track_teacher.html', context = context)
    
    
# def thank(request): 
#     if request.method == "POST":
#         teacher = request.POST.get('teacher_name')
        
#         GDRAT_abs_path =  os.path.join(os.path.dirname(os.path.dirname(__file__)),'projects/media/ex.docx')
#         filee = DocxTemplate(GDRAT_abs_path.replace('\\', '/'))
#         co = {'teacher':teacher}
#         filee.render(co)
#         filee.save('a.docx')
        
#         context = {'teacher':teacher}
#         return render(request, 'projects/thank.html', context=context)
#     else:
#         return render(request, 'projects/thank.html')
        
# import mimetypes
# from django.http.response import HttpResponse


# def draft1(request):
#     base = os.path.dirname(os.path.dirname(os.path.abspath(__file__))).replace('\\', '/')
#     base = base + '/a.docx'
#     content_type_value = 'text/plain'
#     with open(base, 'rb') as fh:
#         response = HttpResponse(
#                 fh.read(),
#                 content_type=content_type_value
#             )

#     response['Content-Disposition'] = "attachment; filename=" + base
#     return response


def examGPT(request):




    if request.method  == 'POST':
        school_name = request.POST.get('school_name')
        grade = request.POST.get('grade')
        subject = request.POST.get('subject')
        lesson_name = request.POST.get('lesson_name')
        teacher_name = request.POST.get('teacher_name')
        topic_language = request.POST.get('topic_language')

projects/templates/projects/ExamGPT.html

{% extends "homepage/base.html" %}

{% block content %} 



<html lang="en">
  <!DOCTYPE html>
  {% load static %}
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Add icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'projects/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'projects/css/style2.css' %}">

    <video autoplay muted loop id="bg-video">
      <source src="{% static 'projects/images/northlightvideo.mp4'%}"  type="video/mp4">
    </video>
    <style>
      body{
        overflow:hidden;
      }
    </style>
  </head>

  
<body class='main-container'> 



  <div class="split left">
      <div class="centered">
          <form action="{% url 'projects:examGPT' %}" method='POST' enctype="multipart/form-data">
              {% csrf_token %}
              <div class="tm-mb-30">
                <input type='text' id="lesson_name" name = 'lesson_name' class='form-control-examgpt rounded-0 border-top-0 border-end-0 border-start-0' placeholder='Lesson Name' required>
              </div>
              <div  class="tm-mb-30">
                <input type='text' id="subject" name = 'subject' class='form-control-examgpt rounded-0 border-top-0 border-end-0 border-start-0' placeholder='Subject' required>
              </div>
              <div class="tm-mb-30">
                <input type='text' id="grade" name = 'grade' class='form-control-examgpt rounded-0 border-top-0 border-end-0 border-start-0' placeholder='Grade' required>
              </div>
              <div class="tm-mb-30">
                  <input type='text' id="school_name" name = 'school_name' class='form-control-examgpt rounded-0 border-top-0 border-end-0 border-start-0' placeholder='School Name' required>
              </div>
              <div class="tm-mb-30">
                <input type='text' id="teacher_name" name = 'teacher_name' class='form-control-examgpt rounded-0 border-top-0 border-end-0 border-start-0' placeholder='Teacher Name' required>
              </div>
          
              <div class="tm-mb-30">
                  <input type='radio' id="topic_language" name = 'topic_language'  value='English'>
                  <label for="topic_language" style = 'color:white'> English </label>
                  <input type='radio' id="topic_language" name = 'topic_language'  value='Arabic' >
                  <label for="topic_language" style = 'color:white'> Arabic </label>
              </div>

          
              <input  type='submit' class="button-89">
          </form> 
      </div>
  </div>
  

  <div class="split right exam_box">
    
    <div class="centered tm-bg-dark intro-left">
      <h5>Generating Quizzes using chatGPT</h5>
      <ul >
        <li> <p> Powered by LLMs.</p></li>
        <li> <p> 10 MC Questions.</p></li>
        <li> <p> Check The Answers.</p></li>
        <li> <p> For quizzes those written in Arabic, Fill All Fields in Arabic.</p></li>
        <li> <p>  للاختبارات القصيرة المكتوبة باللغة العربية ، املأ جميع الحقول باللغة العربية. </p></li>
      </ul>

  </div>

</div>



{% comment %} <div class='whisperLink'>
  <a href = "{% url 'projects:examGPT_voice' %}"  target="_blank"> <input type="button" value="Generate Quizzes Using your Voice"  class="button-89 whisperLink"></a> 
</div>
  <style>
    .whisperLink{ position:relative;
      z-index: 1000; 
      top:300; 
      left:630;   

    }
  </style> {% endcomment %}

  {% if exam_ready_for_downloading %}

    <div class = 'd_buttons'>
        <div>
          <a href = "{% url 'projects:download_exam'  %}">
            <button class="button-89" style='width:300px'> Download Quiz</button>
            </a>
        </div>

      {% if answers_ready_for_downloading %}
        <div> 
          <a href = "{% url 'projects:download_answers'  %}">
          <button class="button-89" style='width:300px'> Download Answers.</button>
          </a>
        </div>
      {% endif %}
    </div>
    {% endif %}

    {% if exam_ready_for_downloading_ar %}

    <div class = 'd_buttons'>
          <a href = "{% url 'projects:download_exam_arabic'  %}">
            <button class="button-89" style='width:300px'> Download Quiz</button>
            </a>
        </div>


    </div>
    {% endif %}








    

</div>

  </body>
  </html>

{% endblock content %} 

projects/templates/projects/track_teacher.html
{% extends "homepage/base.html" %}
{% block content %}
{% load static %}
    
<style>

    body {
        overflow-x: hidden;
      }
</style>

    <body>
        
    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-stacked100@1.0.0"></script>
    <link rel="stylesheet" href="{% static 'projects/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'projects/css/style2.css' %}">


    <div class='my_first_div'>
        <h5>Welocm to Monitoring and Evaluating the Performance of Teachers</h5>
        <p>This project is exclusively working only on Fusion Education Group, MI, US.,  San Marino High School, CA, US.,  Granada Hills Charter High School, CA, US., and all United Arab Emirates Government Schools.</p>
        
        <div style='margin-left:-200px;'>
        <form action="{% url 'projects:track_teacher' %}" method='POST' enctype="multipart/form-data">
            {% csrf_token %}
            <div class='form-group input-file-container'>
                <label for="old" > Insert 1st Checkoint. (e.g., previous semester)</label>
                <input type='file' id="old" name = 'oldfile' class='form-control' required placeholder = 'asa'> 
            </div>
            <div class='form-group input-file-container'> 
                <label for="new"> Insert 2nd Checkoint. (e.g., current semester)</label>
                <input type='file' id='new' name='newfile' class='form-control' required>
            </div>
            <div class='form-group input-file-container' >
                <input class='btn btn-primary'  type='submit' style = "position:absolute; left:0px; top:27px; height:62px">

                <div>
                    {% if report_exist %} 
                    <a href='{% url "projects:send_trackTeachers" %}'><button type="button" class='btn btn-primary' style = "position:relative;top:22px; left:51px;font-size: 13px; padding: 6px 2px; " >Send report to the teachers</button></a>
                    {% else %}
                    <button type="button" class='btn btn-primary' style = "position:relative;top:22px; left:51px;font-size: 13px; padding: 6px 2px; " disabled>Send report to the teachers</button>
                    {% endif %} 
                </div>

                <div>
                    {% if report_exist %} 
                    <a href='{% url "projects:download_teachers_report" %}'><button type="button" class='btn btn-primary' style = "position:relative;top:16px; left:51px;font-size: 13px; padding: 6px 20px; margin-top:2px" >Download   the   Report</button></a>
                    {% else %}
                    <button type="button" class='btn btn-primary' style = "position:relative;top:16px; left:51px;font-size: 13px; padding: 6px 20px; margin-top:2px" disabled>Download   the   Report</button>
                    {% endif %} 
                </div>
            </div>

        </form> 
    </div>
        
    </div>

    {% comment %} chart1 {% endcomment %}
    <div class='chartBox'>
    <canvas id="myChart1"></canvas>
    </div>

    <div class='chartBox'>
        <canvas id="myChart2"></canvas>
    </div>

    <div class='chartBox'>
        <canvas id="myChart3"></canvas>
    </div> 



    <script>
        var ctx = document.getElementById('myChart1').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for x in df_sorted_total_names %} '{{x}}', {% endfor %}],
        datasets: [{
            label: 'Total Points',
            data: [{% for y in total_points %} {{y}}, {% endfor %} ],
            backgroundColor: [ {% for back in background  %} '{{back}}', 
            
            {% endfor %}
            ],
                borderColor: [
                {% for back in background  %} '{{back}}', 
            
                {% endfor %}
                ],
                    borderWidth: 1
        }]
            },
        options: { 
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
        });
    </script> 

    {% comment %} chart2 {% endcomment %}
    <script>
        var ctx = document.getElementById('myChart2').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for x in df_sorted_total_names %} '{{x}}', {% endfor %}],
        datasets: [{
            label: 'Improvement Index',
            data: [{% for y in difference %} {{y}}, {% endfor %} ],
            backgroundColor: [ {% for x in background_difference  %} '{{x}}',  {% endfor %}
            ],
                borderColor: [ {% for x in background_difference  %} '{{x}}',  {% endfor %}
                ],
                    borderWidth: 1
        }]
            },
        options: { 
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
        });
    </script> 

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.1.1/chart.min.js"></script>
    <script>
        var chrt = document.getElementById("myChart3").getContext("2d");
        var chartId = new Chart(chrt, {
            type: 'line',
            data: {
                labels: [{% for x in df_sorted_total_names %} '{{x}}', {% endfor %}],
                datasets: [{
                    label: "previous week",
                    data: [{% for y in total_old %} {{y}}, {% endfor %} ],
                    backgroundColor: ['red'],
                    borderColor: ['black'],
                    borderWidth: 2,
                    pointRadius: 5,
                }, 
                {
                    label: "current week",
                    data: [{% for y in total_new %} {{y}}, {% endfor %} ],
                    backgroundColor: ['yellow'],
                    borderColor: ['blue'],
                    borderWidth: 2,
                    pointRadius: 5,
                }],
            },
            options: {
            },
        });
    </script>
    <script> var count = 0; </script>


    {% comment %} <h2>{{combine}}</h2>
    <h2>{{data}}</h2>
    <h2>{{pieChart_names}}</h2>
    <h2>{{pieChart_IDs}}</h2> {% endcomment %}




<div>
    <div class="chartCard1">
    {% for id, conf_id,data_id  in combine %}

        <div class="chartBox1">
            <canvas id='{{id}}'></canvas>
        </div>

        <script>
            var pie_data = [{% for x in data  %} {{x}},  {% endfor %}];
            var pie_names = [{% for x in pieChart_names  %} '{{x}}', {% endfor %}]

            const {{data_id}} = {

                
                labels: ['% Created Content', '% Discussions', '% Posts','% Questions in Banks', '% Questions in Assessments', '% assessments', '% quizzes', '% Activity', '% Adding Materials' ],
                datasets: [{
                  label: 'Weekly Sales',
                  data: pie_data[count],
                  backgroundColor: [
                    'rgba(128,128,128)',
                    'rgba(30,144,255)',
                    'rgba(0,255,0)',
                    'rgba(250,0,0)',
                    'rgba(255,0,255)',
                    'rgba(255,20,147)',
                    'rgba(0,255,255)', 
                    'rgba(255,255,0)',
                    'rgba(255,150,50)',



                  ],
                  borderColor: [
                    'rgba(128,128,128, 1)',
                    'rgba(30,144,255, 1)',
                    'rgba(0,255,0, 1)',
                    'rgba(250,0,0, 1)',
                    'rgba(255,0,255, 1)',
                    'rgba(255,20,147, 1)',
                    'rgba(0,255,255,1)',
                    'rgba(255,255,0,1)',
                    'rgba(255,150,50)',

                  ],
                  borderWidth: 1
                }]
              };
          
              // config 
              const {{conf_id}} = {
                type: 'pie',
                data:{{data_id}},
                options: {
              

                    plugins:
                    {  title:{
                            display:true, 
                            text: pie_names[count]
                    },
                      
                        legend: {
                            display: false
                        }, 
                    }
                
                }
              };
          
              // render init block
              {{id}} = new Chart(
                document.getElementById('{{id}}'),
                {{conf_id}}                );

                count = count+1;
      </script>
      {% endfor %}

    </div>


</div>    




 


    </body>
    </html>



{% endblock content %}

<h1>hi</h1>



projects/templates/projects/track_teacher_send_reports.html
{% extends "homepage/base.html" %}

{% block content %}

{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>Thank You</title>
	<link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
	<div class="container">
        <img src="{% static 'homepage/images/404-tick.png'%}" alt="">

		<h1>Thank You</h1>
		<p>sent successfully</p>
	</div>

</body>
</html>



<style>

    .container {
        max-width: 600px;
        margin: 0 auto;
        text-align: center;
        padding-top: 50px;
    }
    
    h1 {
        font-size: 3em;
        margin-bottom: 30px;
    }
    
    p {
        font-size: 1.5em;
    }
    
</style>


{% endblock content %}